FROM node:20-alpine

WORKDIR '/app'

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 CMD wget --quiet --tries=1 --spider http://localhost:3000 || exit 1

CMD ["npm", "run", "start"]

